import { NextResponse } from "next/server";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

const SCRIPT = [
  "(() => {",
  "  if (window.ChatbotWidgetLoaded) return;",
  "  window.ChatbotWidgetLoaded = true;",
  "",
  "  const scriptEl = document.currentScript || Array.from(document.getElementsByTagName(\"script\")).pop();",
  "  const apiKey = scriptEl && scriptEl.dataset ? scriptEl.dataset.key : \"\";",
  "  const baseUrl = scriptEl && scriptEl.dataset && scriptEl.dataset.baseUrl",
  "    ? scriptEl.dataset.baseUrl",
  "    : (scriptEl && scriptEl.src ? new URL(scriptEl.src).origin : \"\");",
  "",
  "  if (!apiKey) {",
  "    console.error(\"ChatbotWidget: data-key is required on the script tag.\");",
  "    return;",
  "  }",
  "",
  "  if (!baseUrl) {",
  "    console.error(\"ChatbotWidget: could not resolve base URL.\");",
  "    return;",
  "  }",
  "",
  "  const state = {",
  "    open: false,",
  "    config: null,",
  "    messages: []",
  "  };",
  "",
  "  const ids = {",
  "    root: \"chatbot-widget-root\",",
  "    panel: \"chatbot-widget-panel\",",
  "    toggle: \"chatbot-widget-toggle\",",
  "    messages: \"chatbot-widget-messages\",",
  "    input: \"chatbot-widget-input\",",
  "    send: \"chatbot-widget-send\",",
  "    style: \"chatbot-widget-style\"",
  "  };",
  "",
  "  function injectStyles(primaryColor) {",
  "    if (document.getElementById(ids.style)) return;",
  "    const style = document.createElement(\"style\");",
  "    style.id = ids.style;",
  "    style.textContent =",
  "      \"#\" + ids.root + \" { position: fixed; right: 20px; bottom: 20px; z-index: 99999; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; }\" +",
  "      \"#\" + ids.toggle + \" { width: 56px; height: 56px; border-radius: 50%; border: none; background: \" + primaryColor + \"; color: #fff; cursor: pointer; box-shadow: 0 8px 24px rgba(0,0,0,0.2); }\" +",
  "      \"#\" + ids.panel + \" { width: 320px; height: 420px; background: #fff; border-radius: 14px; box-shadow: 0 16px 40px rgba(0,0,0,0.2); display: none; flex-direction: column; overflow: hidden; margin-bottom: 12px; }\" +",
  "      \"#\" + ids.panel + \".open { display: flex; }\" +",
  "      \"#\" + ids.panel + \" .header { padding: 12px 14px; background: \" + primaryColor + \"; color: #fff; font-weight: 600; }\" +",
  "      \"#\" + ids.panel + \" .messages { flex: 1; padding: 12px; overflow-y: auto; background: #f7f7f7; }\" +",
  "      \"#\" + ids.panel + \" .message { margin: 8px 0; line-height: 1.3; }\" +",
  "      \"#\" + ids.panel + \" .message.user { text-align: right; }\" +",
  "      \"#\" + ids.panel + \" .bubble { display: inline-block; padding: 8px 10px; border-radius: 10px; max-width: 80%; }\" +",
  "      \"#\" + ids.panel + \" .message.user .bubble { background: \" + primaryColor + \"; color: #fff; }\" +",
  "      \"#\" + ids.panel + \" .message.bot .bubble { background: #fff; color: #111; border: 1px solid #e5e5e5; }\" +",
  "      \"#\" + ids.panel + \" .message.loading .bubble { background: #fff; color: #111; border: 1px solid #e5e5e5; }\" +",
  "      \"#\" + ids.panel + \" .typing { display: inline-flex; gap: 4px; align-items: center; height: 12px; }\" +",
  "      \"#\" + ids.panel + \" .typing span { width: 6px; height: 6px; background: #888; border-radius: 50%; display: inline-block; animation: chatbotTyping 1s infinite ease-in-out; }\" +",
  "      \"#\" + ids.panel + \" .typing span:nth-child(2) { animation-delay: 0.2s; }\" +",
  "      \"#\" + ids.panel + \" .typing span:nth-child(3) { animation-delay: 0.4s; }\" +",
  "      \"@keyframes chatbotTyping { 0%, 80%, 100% { transform: scale(0.6); opacity: 0.4; } 40% { transform: scale(1); opacity: 1; } }\" +",
  "      \"#\" + ids.panel + \" .input { display: flex; gap: 8px; padding: 10px; border-top: 1px solid #eee; background: #fff; }\" +",
  "      \"#\" + ids.panel + \" input { flex: 1; padding: 8px 10px; border-radius: 8px; border: 1px solid #ddd; outline: none; }\" +",
  "      \"#\" + ids.panel + \" button.send { padding: 8px 12px; background: \" + primaryColor + \"; color: #fff; border: none; border-radius: 8px; cursor: pointer; }\";",
  "    document.head.appendChild(style);",
  "  }",
  "",
  "  function el(tag, className) {",
  "    const node = document.createElement(tag);",
  "    if (className) node.className = className;",
  "    return node;",
  "  }",
  "",
  "  function appendMessage(role, text) {",
  "    const messagesEl = document.getElementById(ids.messages);",
  "    if (!messagesEl) return;",
  "    const wrap = el(\"div\", \"message \" + role);",
  "    const bubble = el(\"div\", \"bubble\");",
  "    bubble.textContent = text;",
  "    wrap.appendChild(bubble);",
  "    messagesEl.appendChild(wrap);",
  "    messagesEl.scrollTop = messagesEl.scrollHeight;",
  "  }",
  "",
  "  function showTyping() {",
  "    const messagesEl = document.getElementById(ids.messages);",
  "    if (!messagesEl) return null;",
  "    const wrap = el(\"div\", \"message bot loading\");",
  "    const bubble = el(\"div\", \"bubble\");",
  "    const dots = el(\"div\", \"typing\");",
  "    dots.appendChild(el(\"span\"));",
  "    dots.appendChild(el(\"span\"));",
  "    dots.appendChild(el(\"span\"));",
  "    bubble.appendChild(dots);",
  "    wrap.appendChild(bubble);",
  "    messagesEl.appendChild(wrap);",
  "    messagesEl.scrollTop = messagesEl.scrollHeight;",
  "    return wrap;",
  "  }",
  "",
  "  function setOpen(next) {",
  "    state.open = next;",
  "    const panel = document.getElementById(ids.panel);",
  "    if (!panel) return;",
  "    if (state.open) {",
  "      panel.classList.add(\"open\");",
  "    } else {",
  "      panel.classList.remove(\"open\");",
  "    }",
  "  }",
  "",
  "  async function sendMessage(message) {",
  "    if (!message) return;",
  "    appendMessage(\"user\", message);",
  "    const typingEl = showTyping();",
  "    try {",
  "      const res = await fetch(baseUrl + \"/api/chat\", {",
  "        method: \"POST\",",
  "        headers: { \"Content-Type\": \"application/json\" },",
  "        body: JSON.stringify({ apiKey, message })",
  "      });",
  "      const data = await res.json();",
  "      if (typingEl && typingEl.parentNode) typingEl.parentNode.removeChild(typingEl);",
  "      appendMessage(\"bot\", data.reply || \"I don't have that information.\");",
  "    } catch (err) {",
  "      if (typingEl && typingEl.parentNode) typingEl.parentNode.removeChild(typingEl);",
  "      appendMessage(\"bot\", \"Something went wrong. Please try again.\");",
  "    }",
  "  }",
  "",
  "  function buildUI(config) {",
  "    injectStyles(config.theme.primaryColor);",
  "",
  "    const root = el(\"div\");",
  "    root.id = ids.root;",
  "",
  "    const panel = el(\"div\");",
  "    panel.id = ids.panel;",
  "",
  "    const header = el(\"div\", \"header\");",
  "    header.textContent = config.name || \"Chat\";",
  "",
  "    const messages = el(\"div\", \"messages\");",
  "    messages.id = ids.messages;",
  "",
  "    const inputWrap = el(\"div\", \"input\");",
  "    const input = document.createElement(\"input\");",
  "    input.id = ids.input;",
  "    input.type = \"text\";",
  "    input.placeholder = \"Type a message\";",
  "",
  "    const sendBtn = document.createElement(\"button\");",
  "    sendBtn.className = \"send\";",
  "    sendBtn.id = ids.send;",
  "    sendBtn.textContent = \"Send\";",
  "",
  "    inputWrap.appendChild(input);",
  "    inputWrap.appendChild(sendBtn);",
  "",
  "    panel.appendChild(header);",
  "    panel.appendChild(messages);",
  "    panel.appendChild(inputWrap);",
  "",
  "    const toggle = document.createElement(\"button\");",
  "    toggle.id = ids.toggle;",
  "    toggle.textContent = \"Chat\";",
  "",
  "    toggle.addEventListener(\"click\", () => setOpen(!state.open));",
  "    sendBtn.addEventListener(\"click\", () => {",
  "      const value = input.value.trim();",
  "      input.value = \"\";",
  "      sendMessage(value);",
  "    });",
  "    input.addEventListener(\"keydown\", (event) => {",
  "      if (event.key === \"Enter\") {",
  "        const value = input.value.trim();",
  "        input.value = \"\";",
  "        sendMessage(value);",
  "      }",
  "    });",
  "",
  "    root.appendChild(panel);",
  "    root.appendChild(toggle);",
  "    document.body.appendChild(root);",
  "",
  "    if (config.welcomeMessage) {",
  "      appendMessage(\"bot\", config.welcomeMessage);",
  "    }",
  "  }",
  "",
  "  async function init() {",
  "    try {",
  "      const res = await fetch(baseUrl + \"/api/chatbot?key=\" + encodeURIComponent(apiKey));",
  "      const config = await res.json();",
  "      const normalized = {",
  "        name: config.name || \"Chat\",",
  "        theme: { primaryColor: (config.theme && config.theme.primaryColor) || \"#000\" },",
  "        welcomeMessage: config.welcomeMessage || \"Hello! How can I help you?\"",
  "      };",
  "      state.config = normalized;",
  "      buildUI(normalized);",
  "    } catch (err) {",
  "      const fallback = {",
  "        name: \"Chat\",",
  "        theme: { primaryColor: \"#000\" },",
  "        welcomeMessage: \"Hello! How can I help you?\"",
  "      };",
  "      state.config = fallback;",
  "      buildUI(fallback);",
  "    }",
  "  }",
  "",
  "  window.ChatbotWidget = {",
  "    open: () => setOpen(true),",
  "    close: () => setOpen(false),",
  "    toggle: () => setOpen(!state.open),",
  "    send: (message) => sendMessage(String(message || \"\")),",
  "    destroy: () => {",
  "      const root = document.getElementById(ids.root);",
  "      if (root && root.parentNode) root.parentNode.removeChild(root);",
  "      const style = document.getElementById(ids.style);",
  "      if (style && style.parentNode) style.parentNode.removeChild(style);",
  "      window.ChatbotWidgetLoaded = false;",
  "    },",
  "    getConfig: () => state.config",
  "  };",
  "",
  "  init();",
  "})();",
].join("\n");

export async function GET() {
  return new NextResponse(SCRIPT, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      ...CORS_HEADERS,
    },
  });
}

export async function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: CORS_HEADERS });
}
