import { NextResponse } from "next/server";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
};

const SCRIPT = [
  "(() => {",
  "  if (window.ChatbotWidgetLoaded) return;",
  "  window.ChatbotWidgetLoaded = true;",
  "",
  "  const scriptEl = document.currentScript || Array.from(document.getElementsByTagName(\"script\")).pop();",
  "  const apiKey = scriptEl && scriptEl.dataset ? scriptEl.dataset.key : \"\";",
  "  const baseUrl = scriptEl && scriptEl.dataset && scriptEl.dataset.baseUrl",
  "    ? scriptEl.dataset.baseUrl",
  "    : (scriptEl && scriptEl.src ? new URL(scriptEl.src).origin : \"\");",
  "",
  "  if (!apiKey) {",
  "    console.error(\"ChatbotWidget: data-key is required on the script tag.\");",
  "    return;",
  "  }",
  "",
  "  if (!baseUrl) {",
  "    console.error(\"ChatbotWidget: could not resolve base URL.\");",
  "    return;",
  "  }",
  "",
  "  const state = {",
  "    open: false,",
  "    config: null,",
  "    messages: [],",
  "    inFlight: false,",
  "    queue: [],",
  "    isListening: false,",
  "    recognition: null",
  "  };",
  "",
  "  const ids = {",
  "    root: \"chatbot-widget-root\",",
  "    panel: \"chatbot-widget-panel\",",
  "    toggle: \"chatbot-widget-toggle\",",
  "    messages: \"chatbot-widget-messages\",",
  "    input: \"chatbot-widget-input\",",
  "    send: \"chatbot-widget-send\",",
  "    voice: \"chatbot-widget-voice\",",
  "    voiceStatus: \"chatbot-widget-voice-status\",",
  "    style: \"chatbot-widget-style\",",
  "    queue: \"chatbot-widget-queue\"",
  "  };",
  "",
  "  function injectStyles(primaryColor) {",
  "    if (document.getElementById(ids.style)) return;",
  "    const style = document.createElement(\"style\");",
  "    style.id = ids.style;",
  "    style.textContent =",
  "      \"#\" + ids.root + \" { position: fixed; right: 20px; bottom: 20px; z-index: 99999; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; display: flex; flex-direction: column; align-items: flex-end; gap: 10px; }\" +",
  "      \"#\" + ids.toggle + \" { width: 52px; height: 52px; border-radius: 14px; border: none; background: \" + primaryColor + \"; color: #fff; cursor: pointer; box-shadow: 0 10px 24px rgba(0,0,0,0.2); display: inline-flex; align-items: center; justify-content: center; font-size: 20px; }\" +",
  "      \"#\" + ids.panel + \" { width: 320px; height: 520px; background: #fff; border-radius: 16px; box-shadow: 0 20px 50px rgba(0,0,0,0.2); display: none; flex-direction: column; overflow: hidden; }\" +",
  "      \"#\" + ids.panel + \".open { display: flex; }\" +",
  "      \"#\" + ids.panel + \" .header { padding: 12px 12px 10px; background: #fff; color: #111; font-weight: 600; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #eee; }\" +",
  "      \"#\" + ids.panel + \" .header-left { display: inline-flex; align-items: center; gap: 8px; }\" +",
  "      \"#\" + ids.panel + \" .badge { font-size: 10px; padding: 2px 6px; border-radius: 999px; border: 1px solid #ddd; color: #555; }\" +",
  "      \"#\" + ids.panel + \" .queue { font-size: 10px; padding: 2px 6px; border-radius: 999px; border: 1px solid #eee; color: #888; }\" +",
  "      \"#\" + ids.panel + \" .actions { display: inline-flex; gap: 6px; }\" +",
  "      \"#\" + ids.panel + \" .icon-btn { width: 26px; height: 26px; border-radius: 6px; border: none; background: #f2f3f5; color: #555; cursor: pointer; font-size: 16px; line-height: 1; display: inline-flex; align-items: center; justify-content: center; }\" +",
  "      \"#\" + ids.panel + \" .icon-btn:hover { background: #e9eaee; }\" +",
  "      \"#\" + ids.panel + \" .messages { flex: 1; padding: 16px 12px; overflow-y: auto; background: #fff; }\" +",
  "      \"#\" + ids.panel + \" .message { margin: 10px 0; line-height: 1.4; display: flex; gap: 8px; align-items: flex-start; }\" +",
  "      \"#\" + ids.panel + \" .message.user { justify-content: flex-end; }\" +",
  "      \"#\" + ids.panel + \" .message.user .bubble { background: #f1f2f6; color: #111; }\" +",
  "      \"#\" + ids.panel + \" .message.bot .bubble { background: #fff; color: #111; border: 1px solid #ececec; box-shadow: 0 1px 0 rgba(0,0,0,0.02); }\" +",
  "      \"#\" + ids.panel + \" .message.loading .bubble { background: #fff; color: #111; border: 1px solid #ececec; }\" +",
  "      \"#\" + ids.panel + \" .bubble { display: inline-block; padding: 10px 12px; border-radius: 12px; max-width: 78%; font-size: 13px; }\" +",
  "      \"#\" + ids.panel + \" .avatar { width: 24px; height: 24px; border-radius: 999px; background: #5b5bd6; color: #fff; display: inline-flex; align-items: center; justify-content: center; font-size: 14px; flex: 0 0 24px; }\" +",
  "      \"#\" + ids.panel + \" .message.user .avatar { display: none; }\" +",
  "      \"#\" + ids.panel + \" .message.user .bubble { border-radius: 12px 12px 4px 12px; }\" +",
  "      \"#\" + ids.panel + \" .message.bot .bubble { border-radius: 12px 12px 12px 4px; }\" +",
  "      \"#\" + ids.panel + \" .typing { display: inline-flex; gap: 4px; align-items: center; height: 12px; }\" +",
  "      \"#\" + ids.panel + \" .typing span { width: 6px; height: 6px; background: #888; border-radius: 50%; display: inline-block; animation: chatbotTyping 1s infinite ease-in-out; }\" +",
  "      \"#\" + ids.panel + \" .typing span:nth-child(2) { animation-delay: 0.2s; }\" +",
  "      \"#\" + ids.panel + \" .typing span:nth-child(3) { animation-delay: 0.4s; }\" +",
  "      \"@keyframes chatbotTyping { 0%, 80%, 100% { transform: scale(0.6); opacity: 0.4; } 40% { transform: scale(1); opacity: 1; } }\" +",
  "      \"#\" + ids.panel + \" .input { display: flex; gap: 8px; padding: 10px; border-top: 1px solid #eee; background: #fff; align-items: center; }\" +",
  "      \"#\" + ids.panel + \" input { flex: 1; padding: 10px 12px; border-radius: 999px; border: 1px solid #ddd; outline: none; font-size: 13px; min-width: 0; }\" +",
  "      \"#\" + ids.panel + \" button.send { width: 36px; height: 36px; flex: 0 0 36px; background: #eef0f6; color: #333; border: none; border-radius: 999px; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; font-size: 16px; }\" +",
  "      \"#\" + ids.voice + \" { width: 36px; height: 36px; flex: 0 0 36px; background: #eef0f6; color: #555; border: none; border-radius: 999px; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; font-size: 16px; transition: background 0.2s, color 0.2s, box-shadow 0.2s; }\" +",
  "      \"#\" + ids.voice + \".listening { background: #fee2e2; color: #dc2626; box-shadow: 0 0 0 3px rgba(220,38,38,0.2); animation: voicePulse 1.2s ease-in-out infinite; }\" +",
  "      \"#\" + ids.voice + \":hover:not(.listening) { background: #e2e4ed; }\" +",
  "      \"@keyframes voicePulse { 0%, 100% { box-shadow: 0 0 0 3px rgba(220,38,38,0.2); } 50% { box-shadow: 0 0 0 6px rgba(220,38,38,0.08); } }\" +",
  "      \"#\" + ids.voiceStatus + \" { font-size: 11px; color: #dc2626; text-align: center; padding: 4px 10px 0; display: none; font-style: italic; }\" +",
  "      \"#\" + ids.voiceStatus + \".visible { display: block; }\";",
  "    document.head.appendChild(style);",
  "  }",
  "",
  "  function el(tag, className) {",
  "    const node = document.createElement(tag);",
  "    if (className) node.className = className;",
  "    return node;",
  "  }",
  "",
  "  function appendMessage(role, text) {",
  "    const messagesEl = document.getElementById(ids.messages);",
  "    if (!messagesEl) return;",
  "    const wrap = el(\"div\", \"message \" + role);",
  "    const avatar = el(\"div\", \"avatar\");",
  "    avatar.textContent = \"✦\";",
  "    const bubble = el(\"div\", \"bubble\");",
  "    bubble.textContent = text;",
  "    if (role === \"bot\") wrap.appendChild(avatar);",
  "    wrap.appendChild(bubble);",
  "    messagesEl.appendChild(wrap);",
  "    messagesEl.scrollTop = messagesEl.scrollHeight;",
  "  }",
  "",
  "  function showTyping() {",
  "    const messagesEl = document.getElementById(ids.messages);",
  "    if (!messagesEl) return null;",
  "    const wrap = el(\"div\", \"message bot loading\");",
  "    const avatar = el(\"div\", \"avatar\");",
  "    avatar.textContent = \"✦\";",
  "    const bubble = el(\"div\", \"bubble\");",
  "    const dots = el(\"div\", \"typing\");",
  "    dots.appendChild(el(\"span\"));",
  "    dots.appendChild(el(\"span\"));",
  "    dots.appendChild(el(\"span\"));",
  "    bubble.appendChild(dots);",
  "    wrap.appendChild(avatar);",
  "    wrap.appendChild(bubble);",
  "    messagesEl.appendChild(wrap);",
  "    messagesEl.scrollTop = messagesEl.scrollHeight;",
  "    return wrap;",
  "  }",
  "",
  "  function updateQueueBadge() {",
  "    const badge = document.getElementById(ids.queue);",
  "    if (!badge) return;",
  "    const count = state.queue.length;",
  "    if (count > 0) {",
  "      badge.textContent = \"Queued: \" + count;",
  "      badge.style.display = \"inline-flex\";",
  "    } else {",
  "      badge.style.display = \"none\";",
  "    }",
  "  }",
  "",
  "  function setOpen(next) {",
  "    state.open = next;",
  "    const panel = document.getElementById(ids.panel);",
  "    if (!panel) return;",
  "    if (state.open) {",
  "      panel.classList.add(\"open\");",
  "    } else {",
  "      panel.classList.remove(\"open\");",
  "      stopVoice();",
  "    }",
  "  }",
  "",
  "  async function processQueue() {",
  "    if (state.inFlight) return;",
  "    state.inFlight = true;",
  "    while (state.queue.length > 0) {",
  "      updateQueueBadge();",
  "      const next = state.queue.shift();",
  "      if (!next) continue;",
  "      const typingEl = showTyping();",
  "      try {",
  "        const res = await fetch(baseUrl + \"/api/chat\", {",
  "          method: \"POST\",",
  "          headers: { \"Content-Type\": \"application/json\" },",
  "          body: JSON.stringify({ apiKey, message: next })",
  "        });",
  "        const data = await res.json();",
  "        if (typingEl && typingEl.parentNode) typingEl.parentNode.removeChild(typingEl);",
  "        appendMessage(\"bot\", data.reply || \"I don't have that information.\");",
  "      } catch (err) {",
  "        if (typingEl && typingEl.parentNode) typingEl.parentNode.removeChild(typingEl);",
  "        appendMessage(\"bot\", \"Something went wrong. Please try again.\");",
  "      }",
  "    }",
  "    state.inFlight = false;",
  "    updateQueueBadge();",
  "  }",
  "",
  "  async function sendMessage(message) {",
  "    if (!message) return;",
  "    appendMessage(\"user\", message);",
  "    state.queue.push(message);",
  "    updateQueueBadge();",
  "    processQueue();",
  "  }",
  "",
  "  function setVoiceStatus(text, visible) {",
  "    const el = document.getElementById(ids.voiceStatus);",
  "    if (!el) return;",
  "    el.textContent = text || \"\";",
  "    if (visible) { el.classList.add(\"visible\"); }",
  "    else { el.classList.remove(\"visible\"); }",
  "  }",
  "",
  "  function setVoiceListening(listening) {",
  "    state.isListening = listening;",
  "    const btn = document.getElementById(ids.voice);",
  "    if (!btn) return;",
  "    if (listening) {",
  "      btn.classList.add(\"listening\");",
  "      btn.setAttribute(\"aria-label\", \"Stop listening\");",
  "      btn.textContent = \"⏹\";",
  "      setVoiceStatus(\"Listening… speak now\", true);",
  "    } else {",
  "      btn.classList.remove(\"listening\");",
  "      btn.setAttribute(\"aria-label\", \"Start voice input\");",
  "      btn.textContent = \"🎤\";",
  "      setVoiceStatus(\"\", false);",
  "    }",
  "  }",
  "",
  "  function stopVoice() {",
  "    if (state.recognition) {",
  "      try { state.recognition.stop(); } catch(e) {}",
  "    }",
  "    setVoiceListening(false);",
  "  }",
  "",
  "  function startVoice() {",
  "    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;",
  "    if (!SpeechRecognition) {",
  "      setVoiceStatus(\"Voice not supported in this browser\", true);",
  "      setTimeout(() => setVoiceStatus(\"\", false), 3000);",
  "      return;",
  "    }",
  "",
  "    if (state.isListening) {",
  "      stopVoice();",
  "      return;",
  "    }",
  "",
  "    const recognition = new SpeechRecognition();",
  "    recognition.lang = \"en-US\";",
  "    recognition.interimResults = true;",
  "    recognition.maxAlternatives = 1;",
  "    recognition.continuous = false;",
  "    state.recognition = recognition;",
  "",
  "    recognition.onstart = function() {",
  "      setVoiceListening(true);",
  "    };",
  "",
  "    recognition.onresult = function(event) {",
  "      let interim = \"\";",
  "      let final = \"\";",
  "      for (let i = event.resultIndex; i < event.results.length; i++) {",
  "        const transcript = event.results[i][0].transcript;",
  "        if (event.results[i].isFinal) { final += transcript; }",
  "        else { interim += transcript; }",
  "      }",
  "      const input = document.getElementById(ids.input);",
  "      if (input) {",
  "        input.value = final || interim;",
  "      }",
  "      if (final) {",
  "        setVoiceStatus(\"Got it!\", true);",
  "        setTimeout(() => setVoiceStatus(\"\", false), 1000);",
  "      }",
  "    };",
  "",
  "    recognition.onerror = function(event) {",
  "      setVoiceListening(false);",
  "      let msg = \"Voice error\";",
  "      if (event.error === \"not-allowed\" || event.error === \"denied\") { msg = \"Microphone access denied\"; }",
  "      else if (event.error === \"no-speech\") { msg = \"No speech detected\"; }",
  "      else if (event.error === \"network\") { msg = \"Network error\"; }",
  "      setVoiceStatus(msg, true);",
  "      setTimeout(() => setVoiceStatus(\"\", false), 3000);",
  "    };",
  "",
  "    recognition.onend = function() {",
  "      setVoiceListening(false);",
  "      const input = document.getElementById(ids.input);",
  "      if (input && input.value.trim()) {",
  "        const value = input.value.trim();",
  "        input.value = \"\";",
  "        sendMessage(value);",
  "      }",
  "    };",
  "",
  "    recognition.start();",
  "  }",
  "",
  "  function buildUI(config) {",
  "    injectStyles(config.theme.primaryColor);",
  "",
  "    const root = el(\"div\");",
  "    root.id = ids.root;",
  "",
  "    const panel = el(\"div\");",
  "    panel.id = ids.panel;",
  "",
  "    const header = el(\"div\", \"header\");",
  "    const headerLeft = el(\"div\", \"header-left\");",
  "    const title = el(\"div\");",
  "    title.textContent = config.name || \"Chat\";",
  "    const badge = el(\"div\", \"badge\");",
  "    badge.textContent = \"built-in\";",
  "    const queue = el(\"div\", \"queue\");",
  "    queue.id = ids.queue;",
  "    queue.style.display = \"none\";",
  "    const actions = el(\"div\", \"actions\");",
  "    const minimizeBtn = document.createElement(\"button\");",
  "    minimizeBtn.className = \"icon-btn\";",
  "    minimizeBtn.type = \"button\";",
  "    minimizeBtn.setAttribute(\"aria-label\", \"Minimize\");",
  "    minimizeBtn.textContent = \"–\";",
  "    actions.appendChild(minimizeBtn);",
  "    headerLeft.appendChild(title);",
  "    headerLeft.appendChild(badge);",
  "    headerLeft.appendChild(queue);",
  "    header.appendChild(headerLeft);",
  "    header.appendChild(actions);",
  "",
  "    const messages = el(\"div\", \"messages\");",
  "    messages.id = ids.messages;",
  "",
  "    // Voice status bar (above input row)",
  "    const voiceStatus = el(\"div\");",
  "    voiceStatus.id = ids.voiceStatus;",
  "",
  "    const inputWrap = el(\"div\", \"input\");",
  "    const input = document.createElement(\"input\");",
  "    input.id = ids.input;",
  "    input.type = \"text\";",
  "    input.placeholder = \"Type or speak a message\";",
  "",
  "    const voiceBtn = document.createElement(\"button\");",
  "    voiceBtn.id = ids.voice;",
  "    voiceBtn.type = \"button\";",
  "    voiceBtn.textContent = \"🎤\";",
  "    voiceBtn.setAttribute(\"aria-label\", \"Start voice input\");",
  "    voiceBtn.title = \"Voice input\";",
  "",
  "    const sendBtn = document.createElement(\"button\");",
  "    sendBtn.className = \"send\";",
  "    sendBtn.id = ids.send;",
  "    sendBtn.textContent = \"→\";",
  "",
  "    inputWrap.appendChild(input);",
  "    inputWrap.appendChild(voiceBtn);",
  "    inputWrap.appendChild(sendBtn);",
  "",
  "    panel.appendChild(header);",
  "    panel.appendChild(messages);",
  "    panel.appendChild(voiceStatus);",
  "    panel.appendChild(inputWrap);",
  "",
  "    const toggle = document.createElement(\"button\");",
  "    toggle.id = ids.toggle;",
  "    toggle.textContent = \"Chat\";",
  "",
  "    toggle.addEventListener(\"click\", () => setOpen(!state.open));",
  "    minimizeBtn.addEventListener(\"click\", () => setOpen(false));",
    "    voiceBtn.addEventListener(\"click\", () => { setOpen(true); startVoice(); });",
  "    sendBtn.addEventListener(\"click\", () => {",
  "      stopVoice();",
  "      const value = input.value.trim();",
  "      input.value = \"\";",
  "      sendMessage(value);",
  "    });",
  "    input.addEventListener(\"keydown\", (event) => {",
  "      if (event.key === \"Enter\") {",
  "        stopVoice();",
  "        const value = input.value.trim();",
  "        input.value = \"\";",
  "        sendMessage(value);",
  "      }",
  "    });",
  "",
  "    root.appendChild(panel);",
  "    root.appendChild(toggle);",
  "    document.body.appendChild(root);",
  "",
  "    if (config.welcomeMessage) {",
  "      appendMessage(\"bot\", config.welcomeMessage);",
  "    }",
  "  }",
  "",
  "  async function init() {",
  "    try {",
  "      const res = await fetch(baseUrl + \"/api/chatbot?key=\" + encodeURIComponent(apiKey));",
  "      const config = await res.json();",
  "      const normalized = {",
  "        name: config.name || \"Chat\",",
  "        theme: { primaryColor: (config.theme && config.theme.primaryColor) || \"#000\" },",
  "        welcomeMessage: config.welcomeMessage || \"Hello! How can I help you?\"",
  "      };",
  "      state.config = normalized;",
  "      buildUI(normalized);",
  "    } catch (err) {",
  "      const fallback = {",
  "        name: \"Chat\",",
  "        theme: { primaryColor: \"#000\" },",
  "        welcomeMessage: \"Hello! How can I help you?\"",
  "      };",
  "      state.config = fallback;",
  "      buildUI(fallback);",
  "    }",
  "  }",
  "",
  "  window.ChatbotWidget = {",
  "    open: () => setOpen(true),",
  "    close: () => setOpen(false),",
  "    toggle: () => setOpen(!state.open),",
  "    send: (message) => sendMessage(String(message || \"\")),",
  "    destroy: () => {",
  "      stopVoice();",
  "      const root = document.getElementById(ids.root);",
  "      if (root && root.parentNode) root.parentNode.removeChild(root);",
  "      const style = document.getElementById(ids.style);",
  "      if (style && style.parentNode) style.parentNode.removeChild(style);",
  "      window.ChatbotWidgetLoaded = false;",
  "    },",
  "    getConfig: () => state.config",
  "  };",
  "",
  "  init();",
  "})();",
].join("\n");

export async function GET() {
  return new NextResponse(SCRIPT, {
    status: 200,
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      ...CORS_HEADERS,
    },
  });
}

export async function OPTIONS() {
  return new NextResponse(null, { status: 204, headers: CORS_HEADERS });
}